<a href="https://colab.research.google.com/github/Rajasri1011-v/STUDENT-PERFORMANCE/blob/main/ml_cohort__2__ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load the data

### Subtask:
Loading the "/Student_performance_data _.csv" file into a pandas DataFrame.


In [ ]:
import pandas as pd

df = pd.read_csv("/Student_performance_data _.csv")

In [ ]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3.042915         1.0  
2             0  0.112602         4.0  
3             0  2.054218         3.0  
4             0  1.288061         4.0

## Explore and preprocess the data



In [ ]:
print(df.info())
print(df.isnull().sum())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   StudentID          2392 non-null   int64  
 1   Age                2392 non-null   int64  
 2   Gender             2392 non-null   int64  
 3   Ethnicity          2392 non-null   int64  
 4   ParentalEducation  2392 non-null   int64  
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64  
 7   Tutoring           2392 non-null   int64  
 8   ParentalSupport    2392 non-null   int64  
 9   Extracurricular    2392 non-null   int64  
 10  Sports             2392 non-null   int64  
 11  Music              2392 non-null   int64  
 12  Volunteering       2392 non-null   int64  
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB
None
StudentID          

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3.042915         1.0  
2             0  0.112602         4.0  
3             0  2.054218         3.0  
4             0  1.288061         4.0


Based on the output, there are no missing values in the dataset. The columns 'Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', and 'Volunteering' appear to be categorical. I will one-hot encode these categorical features, separate the features (X) and the target variable (y), and then split the data into training and testing sets.



In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

categorical_features = ['Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering']
df_encoded = pd.get_dummies(df, columns=categorical_features, drop_first=True)

X = df_encoded.drop(['StudentID', 'GPA', 'GradeClass'], axis=1)
y_regression = df_encoded['GPA']
y_classification = df_encoded['GradeClass']

X_train, X_test, y_regression_train, y_regression_test = train_test_split(X, y_regression, test_size=0.2, random_state=42)
X_train, X_test, y_classification_train, y_classification_test = train_test_split(X, y_classification, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_regression_train:", y_regression_train.shape)
print("Shape of y_regression_test:", y_regression_test.shape)
print("Shape of y_classification_train:", y_classification_train.shape)
print("Shape of y_classification_test:", y_classification_test.shape)

Shape of X_train: (1913, 20)
Shape of X_test: (479, 20)
Shape of y_regression_train: (1913,)
Shape of y_regression_test: (479,)
Shape of y_classification_train: (1913,)
Shape of y_classification_test: (479,)


## Introduce linear regression

### Subtask:
Explain the concept of Linear Regression and its applications.


**Reasoning**:
Provide an explanation of Linear Regression, including its concept, mathematical forms, and applications, as requested in the subtask instructions.



In [ ]:
print("Linear Regression Explained:\n")

print("1. Concept:")
print("Linear Regression is a statistical method used to model the linear relationship between a dependent variable (the variable we want to predict) and one or more independent variables (the variables used for prediction). The goal is to find the best-fitting straight line (or hyperplane in higher dimensions) that describes how the dependent variable changes as the independent variables change.")
print("\n2. Mathematical Forms:")
print("   - Simple Linear Regression (one independent variable):")
print("     The equation is typically represented as: y = mx + b")
print("     - y: The dependent variable.")
print("     - m: The slope of the line, representing the change in y for a one-unit change in x.")
print("     - x: The independent variable.")
print("     - b: The y-intercept, representing the value of y when x is 0.")
print("\n   - Multiple Linear Regression (multiple independent variables):")
print("     The equation is an extension of simple linear regression:")
print("     y = b0 + b1*x1 + b2*x2 + ... + bn*xn")
print("     - y: The dependent variable.")
print("     - b0: The y-intercept (or bias term), representing the value of y when all independent variables are 0.")
print("     - b1, b2, ..., bn: The coefficients (or weights) for each independent variable (x1, x2, ..., xn). Each coefficient represents the change in y for a one-unit change in the corresponding independent variable, holding other variables constant.")
print("     - x1, x2, ..., xn: The independent variables.")
print("\n3. Applications:")
print("Linear Regression is widely used in various fields, including:")
print("   - Economics: Predicting economic growth, inflation rates, or unemployment based on various indicators.")
print("   - Finance: Forecasting stock prices, analyzing the relationship between risk and return.")
print("   - Marketing: Predicting sales based on advertising spending, analyzing the impact of promotions.")
print("   - Healthcare: Predicting patient outcomes based on various factors like age, weight, and treatment.")
print("   - Real Estate: Predicting house prices based on features like size, location, and number of bedrooms.")
print("   - Education: Analyzing the relationship between study time, absences, and student performance (like GPA).")

Linear Regression Explained:

1. Concept:
Linear Regression is a statistical method used to model the linear relationship between a dependent variable (the variable we want to predict) and one or more independent variables (the variables used for prediction). The goal is to find the best-fitting straight line (or hyperplane in higher dimensions) that describes how the dependent variable changes as the independent variables change.

2. Mathematical Forms:
   - Simple Linear Regression (one independent variable):
     The equation is typically represented as: y = mx + b
     - y: The dependent variable.
     - m: The slope of the line, representing the change in y for a one-unit change in x.
     - x: The independent variable.
     - b: The y-intercept, representing the value of y when x is 0.

   - Multiple Linear Regression (multiple independent variables):
     The equation is an extension of simple linear regression:
     y = b0 + b1*x1 + b2*x2 + ... + bn*xn
     - y: The dependent v

## Implement and train linear regression

### Subtask:
Building  and training a Linear Regression model on the data.


In [ ]:
from sklearn.linear_model import LinearRegression

# Instantiate a Linear Regression object
linear_regression_model = LinearRegression()

# Fit the model to the training data
linear_regression_model.fit(X_train, y_regression_train)

LinearRegression()

## Evaluate linear regression




Importing the necessary regression evaluation metrics, make predictions using the trained linear regression model, calculate MAE, MSE, and R-squared, and print the results.



In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_regression_pred = linear_regression_model.predict(X_test)

mae = mean_absolute_error(y_regression_test, y_regression_pred)
mse = mean_squared_error(y_regression_test, y_regression_pred)
r2 = r2_score(y_regression_test, y_regression_pred)

print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"R-squared (R2): {r2:.4f}")

Mean Absolute Error (MAE): 0.1551
Mean Squared Error (MSE): 0.0385
R-squared (R2): 0.9534


## Introduce logistic regression

### Subtask:
Explaing the concept of Logistic Regression and its applications, particularly for classification tasks.


**Reasoning**:
Print the explanation of Logistic Regression, its mathematical form, and applications as requested in the instructions.



In [ ]:
print("Logistic Regression Explained:\n")

print("1. Concept:")
print("Logistic Regression is a statistical model used for binary classification problems, meaning it predicts the probability that an observation belongs to one of two classes. Unlike Linear Regression which predicts a continuous outcome, Logistic Regression predicts the probability of a categorical outcome. It models the relationship between the independent variables and the probability of the dependent variable belonging to a particular class.")
print("\n2. Mathematical Form (Sigmoid Function):")
print("The core of Logistic Regression is the sigmoid function (also known as the logistic function). This function maps any real-valued number to a value between 0 and 1, which can be interpreted as a probability.")
print("The sigmoid function is defined as: σ(z) = 1 / (1 + e^(-z))")
print("Where:")
print("   - σ(z): The output of the sigmoid function, representing the predicted probability.")
print("   - e: The base of the natural logarithm (approximately 2.71828).")
print("   - z: A linear combination of the independent variables and their coefficients, similar to the linear equation in Linear Regression: z = b0 + b1*x1 + b2*x2 + ... + bn*xn")
print("The output of the sigmoid function, σ(z), is then used to classify the observation. If σ(z) is greater than a certain threshold (commonly 0.5), the observation is assigned to one class, otherwise to the other class.")
print("\n3. Applications:")
print("Logistic Regression is widely used in various classification tasks, including:")
print("   - Healthcare: Predicting the probability of a disease based on symptoms and patient history.")
print("   - Finance: Predicting the likelihood of loan default based on credit score and financial history.")
print("   - Marketing: Predicting whether a customer will click on an advertisement or purchase a product.")
print("   - Spam Detection: Classifying emails as spam or not spam based on their content.")
print("   - Image Recognition: Classifying images into different categories (though deep learning models are more common for complex image tasks).")
print("   - Education: Predicting whether a student will pass or fail a course based on factors like study time and attendance.")

Logistic Regression Explained:

1. Concept:
Logistic Regression is a statistical model used for binary classification problems, meaning it predicts the probability that an observation belongs to one of two classes. Unlike Linear Regression which predicts a continuous outcome, Logistic Regression predicts the probability of a categorical outcome. It models the relationship between the independent variables and the probability of the dependent variable belonging to a particular class.

2. Mathematical Form (Sigmoid Function):
The core of Logistic Regression is the sigmoid function (also known as the logistic function). This function maps any real-valued number to a value between 0 and 1, which can be interpreted as a probability.
The sigmoid function is defined as: σ(z) = 1 / (1 + e^(-z))
Where:
   - σ(z): The output of the sigmoid function, representing the predicted probability.
   - e: The base of the natural logarithm (approximately 2.71828).
   - z: A linear combination of the indep

## Implement and train logistic regression

### Subtask:
Building and training a Logistic Regression model on the data.



Build and train a Logistic Regression model on the training data as instructed.



In [ ]:
from sklearn.linear_model import LogisticRegression

# Instantiate a Logistic Regression object
logistic_regression_model = LogisticRegression(max_iter=1000)

# Fit the Logistic Regression model to the training data
logistic_regression_model.fit(X_train, y_classification_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

## Evaluate logistic regression

### Subtask:



Calculate and print the accuracy, F1-score, and confusion matrix for the logistic regression model's predictions on the test set.



In [ ]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Make predictions on the test set
y_classification_pred = logistic_regression_model.predict(X_test)

# Calculate and print Accuracy
accuracy = accuracy_score(y_classification_test, y_classification_pred)
print(f"Accuracy: {accuracy:.4f}")

# Calculate and print F1-score (weighted for multi-class)
f1 = f1_score(y_classification_test, y_classification_pred, average='weighted')
print(f"F1-score (weighted): {f1:.4f}")

# Calculate and print Confusion Matrix
conf_matrix = confusion_matrix(y_classification_test, y_classification_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.6764
F1-score (weighted): 0.6519

Confusion Matrix:
[[  0  14   4   2   2]
 [  4  23  16   2   4]
 [  1  14  46  18   6]
 [  1   2  22  29  32]
 [  0   1   2   8 226]]


## End-to-end ml model

### Subtask:
Guide the user through building a complete ML project using either Linear or Logistic Regression, including data loading, preprocessing, model training, evaluation, and making predictions.


**Reasoning**:
I need to guide the user through building an end-to-end ML project using either Linear or Logistic Regression, including data loading, preprocessing, model training, evaluation, and making predictions. Based on the previous successful steps and the available variables, I will choose the Logistic Regression model as it demonstrates classification, which involves additional evaluation metrics like F1-score and confusion matrix beyond just continuous error measures. I will structure the response to cover the requested points: introduction, recap of previous steps, model description, training, evaluation, and prediction. I will then make predictions using the trained logistic regression model on the test set.



In [ ]:
# 2. Write a brief introduction explaining the goal of this end-to-end project
print("End-to-End Machine Learning Project: Predicting Student Grade Class using Logistic Regression\n")
print("The goal of this project is to build and evaluate a machine learning model to predict the Grade Class of students based on various factors such as age, study time, absences, demographics, and extracurricular activities. We will use Logistic Regression, a suitable model for classification tasks, to achieve this.")

# 3. Recap the data loading and preprocessing steps that were performed earlier
print("\nRecap of Data Loading and Preprocessing:")
print("We started by loading the student performance data from the provided CSV file into a pandas DataFrame (`df`).")
print("We then explored the dataset, handled missing values (none were found), and encoded categorical features using one-hot encoding (`df_encoded`).")
print("Finally, we split the data into features (`X`) and the target variable (`y_classification` for Grade Class prediction) and further divided these into training and testing sets (`X_train`, `X_test`, `y_classification_train`, `y_classification_test`).")
print(f"The shapes of the training and testing sets are: X_train {X_train.shape}, X_test {X_test.shape}, y_classification_train {y_classification_train.shape}, y_classification_test {y_classification_test.shape}")

# 4. Describe the chosen model (Logistic Regression) and explain why it is suitable
print("\nChosen Model: Logistic Regression")
print("We chose Logistic Regression for this project because the task is a classification problem: predicting the Grade Class, which is a categorical variable. Logistic Regression is a powerful and interpretable algorithm well-suited for modeling the probability of an outcome belonging to a particular class based on the input features.")

# 5. Show how the chosen model was trained, referencing the trained model object
print("\nModel Training:")
print("We instantiated a Logistic Regression model (`logistic_regression_model`) and trained it using the training data (`X_train`, `y_classification_train`).")
# The training was done in a previous step, the model object `logistic_regression_model` is available in the kernel.

# 6. Explain the evaluation metrics used and present the results
print("\nModel Evaluation:")
print("To evaluate the performance of our Logistic Regression model, we used the following metrics:")
print("  - Accuracy: The proportion of correctly classified instances.")
print("  - F1-score (weighted): The harmonic mean of precision and recall, providing a balanced measure of the model's performance, especially useful in multi-class classification with potential class imbalance.")
print("  - Confusion Matrix: A table that summarizes the performance of a classification model by showing the counts of true positive, true negative, false positive, and false negative predictions for each class.")
print(f"The previously calculated evaluation results on the test set are:")
print(f"  - Accuracy: {accuracy:.4f}")
print(f"  - F1-score (weighted): {f1:.4f}")
print("\nConfusion Matrix:")
display(conf_matrix) # Displaying the confusion matrix table

# 7. Demonstrate how to make predictions
print("\nMaking Predictions:")
print("Now, we will use the trained Logistic Regression model to make predictions on the unseen test set (`X_test`).")
final_predictions = logistic_regression_model.predict(X_test)
print("Predictions have been made and stored in the `final_predictions` variable.")

# 8. Explain what these predictions represent
print("\nInterpretation of Predictions:")
print("The `final_predictions` variable contains the predicted Grade Class for each student in the test set. These predictions are the output of the Logistic Regression model, indicating the most likely Grade Class (0, 1, 2, 3, or 4) for each student based on their features.")

End-to-End Machine Learning Project: Predicting Student Grade Class using Logistic Regression

The goal of this project is to build and evaluate a machine learning model to predict the Grade Class of students based on various factors such as age, study time, absences, demographics, and extracurricular activities. We will use Logistic Regression, a suitable model for classification tasks, to achieve this.

Recap of Data Loading and Preprocessing:
We started by loading the student performance data from the provided CSV file into a pandas DataFrame (`df`).
We then explored the dataset, handled missing values (none were found), and encoded categorical features using one-hot encoding (`df_encoded`).
Finally, we split the data into features (`X`) and the target variable (`y_classification` for Grade Class prediction) and further divided these into training and testing sets (`X_train`, `X_test`, `y_classification_train`, `y_classification_test`).
The shapes of the training and testing sets ar

array([[  0,  14,   4,   2,   2],
       [  4,  23,  16,   2,   4],
       [  1,  14,  46,  18,   6],
       [  1,   2,  22,  29,  32],
       [  0,   1,   2,   8, 226]])


Making Predictions:
Now, we will use the trained Logistic Regression model to make predictions on the unseen test set (`X_test`).
Predictions have been made and stored in the `final_predictions` variable.

Interpretation of Predictions:
The `final_predictions` variable contains the predicted Grade Class for each student in the test set. These predictions are the output of the Logistic Regression model, indicating the most likely Grade Class (0, 1, 2, 3, or 4) for each student based on their features.
